results = sweep_and_plot( ...
  'varnames', {'Q_dot','ROF'}, ...
  'ranges', {[3.5e6, 4.5e6],[3,3.5]}, ...
  'npoints', [10,5], ...
  'plotvars', struct('P_Pump_LCH4',1,'P_Pump_LOx',1,'delta_p_pump_LCH4',1), ...
  'probes', {'fuel.Cooling_Channels.T'}, ...
  'autoplot', true, ...
  'verbose', true);