% do different graphs coloured
% implement requirements as lookup table

results = sweep_and_plot( ...
  'varnames', {'Q_dot', 'ROF'}, ...
  'ranges', {[2e6, 13e6], [3.09, 3.09]}, ...´
  'npoints', [50, 1], ...
  'plotvars', struct('P_Pump_LCH4',1,'P_Pump_LOx',1,'delta_p_pump_LCH4',1), ...
  'probes', {'fuel.Cooling_Channels.p'}, ...
  'autoplot', true, ...
  'verbose', true);