% do different graphs coloured
% implement requirements as lookup table

results = sweep_and_plot( ...
  'varnames', {'Q_dot', 'ROF'}, ...
  'ranges', {[4e6, 8e6], [2.9, 3.2]}, ...´
  'npoints', [10, 6], ...
  'plotvars', struct('P_Pump_LCH4',1,'P_Pump_LOx',1,'delta_p_pump_LCH4',1), ...
  'probes', {'fuel.Cooling_Channels.p'}, ...
  'autoplot', true, ...
  'verbose', true);